[package]
name = "foundation"
version.workspace = true
edition.workspace = true

[features]
default = []
nightly = ["cfg_select", "new_range_api"]
associated_type_defaults = []
cfg_select = []
new_range_api = []

[dependencies]
libc = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { workspace = true }
